Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-10, with the labels that each got.

#238 Bugfixes, Improvements, Stability and more bugs
  README.md
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/backups.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/log_channel.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/sql/welcome_sql.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/modules/welcome.py
  SaitamaRobot/sample_config.py
  app.json
  runtime.txt
Labels: Code Formatting, bug fix, critical bug, enhancement, more coffee needed

#243 More more stuff to be added to master.
  README.md
  SaitamaRobot/modules/animation.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/disable.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/welcome.py
  SaitamaRobot/sample_config.py
  requirements.txt
Labels: Code Formatting, bug fix, enhancement, major change, more coffee needed, translation improvement

#253 clearall command
  SaitamaRobot/modules/notes.py
Labels: enhancement

#256 Fixed chatlist command
  SaitamaRobot/modules/users.py
Labels: bug fix

#257 Added conformation buttons in removeallfilters.
  SaitamaRobot/modules/cust_filters.py
Labels: enhancement

#260 Bring more features, fixes and stability to master branch
  .github/disabled/docker_disabled.yml
  .github/disabled/main.yml
  README.md
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/afk.py
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/antiflood.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/cleaner.py
  SaitamaRobot/modules/connection.py
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/debug.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/helper_funcs/extraction.py
  SaitamaRobot/modules/helper_funcs/filters.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/helper_funcs/telethn/__init__.py
  SaitamaRobot/modules/helper_funcs/telethn/chatstatus.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/log.py
  SaitamaRobot/modules/muting.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/reporting.py
  SaitamaRobot/modules/sql/welcome_sql.py
  SaitamaRobot/modules/stickers.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/modules/welcome.py
  SaitamaRobot/sample_config.py
  app.json
  requirements.txt
Labels: Code Formatting, bug fix, critical bug, documentation, enhancement, translation improvement

#267 Bring some upgrades and bugfixes to master branch
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/gtranslator.py
  SaitamaRobot/modules/purge.py
  SaitamaRobot/modules/users.py
Labels: Code Formatting, bug fix, enhancement
