Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-12, with the labels that each got.

#305 [disasters] Corrected a small typo
  SaitamaRobot/modules/disasters.py
Labels: translation improvement

#310 Use perf_timer for timer logic in admincache
  SaitamaRobot/modules/helper_funcs/chat_status.py
Labels: bug fix

#318 Added a new fun command
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/fun_strings.py
Labels: enhancement

#331 [new-feature] Added approval module
  SaitamaRobot/modules/antiflood.py
  SaitamaRobot/modules/approve.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/sql/approve_sql.py
  SaitamaRobot/modules/warns.py
Labels: enhancement

#337 minor fixes
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/afk.py
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/antiflood.py
  SaitamaRobot/modules/approve.py
  SaitamaRobot/modules/backups.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/cleaner.py
  SaitamaRobot/modules/helper_funcs/__init__.py
  SaitamaRobot/modules/helper_funcs/alternate.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/helper_funcs/extraction.py
  SaitamaRobot/modules/helper_funcs/filters.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/helper_funcs/misc.py
  SaitamaRobot/modules/helper_funcs/msg_types.py
  SaitamaRobot/modules/helper_funcs/string_handling.py
  SaitamaRobot/modules/helper_funcs/telethn/__init__.py
  SaitamaRobot/modules/helper_funcs/telethn/chatstatus.py
  SaitamaRobot/modules/modules.py
Labels: Code Formatting, enhancement

#338 [anime] Fixed bad url string in /kaizoku responses
  SaitamaRobot/modules/anime.py
Labels: bug fix
