Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-06, with the labels that each got.

#63 More bug fixes and tuneups.
  app.json
  requirements.txt
  tg_bot/__init__.py
  tg_bot/modules/admin.py
  tg_bot/modules/afk.py
  tg_bot/modules/animation.py
  tg_bot/modules/anime.py
  tg_bot/modules/antiflood.py
  tg_bot/modules/bans.py
  tg_bot/modules/blacklist.py
  tg_bot/modules/blacklist_stickers.py
  tg_bot/modules/chatbot.py
  tg_bot/modules/cleaner.py
  tg_bot/modules/connection.py
  tg_bot/modules/currency_converter.py
  tg_bot/modules/cust_filters.py
  tg_bot/modules/disable.py
  tg_bot/modules/disasters.py
  tg_bot/modules/feds.py
  tg_bot/modules/fun.py
  tg_bot/modules/gettime.py
  tg_bot/modules/global_bans.py
  tg_bot/modules/grammar_correction.py
  tg_bot/modules/gtranslator.py
  tg_bot/modules/helper_funcs/misc.py
  tg_bot/modules/locks.py
  tg_bot/modules/log_channel.py
  tg_bot/modules/math.py
  tg_bot/modules/misc.py
  tg_bot/modules/muting.py
  tg_bot/modules/notes.py
  tg_bot/modules/paste.py
  tg_bot/modules/ping.py
  tg_bot/modules/purge.py
  tg_bot/modules/reactions.py
  tg_bot/modules/reporting.py
  tg_bot/modules/rss.py
  tg_bot/modules/rules.py
  tg_bot/modules/sed.py
  tg_bot/modules/shell.py
  tg_bot/modules/shout.py
  tg_bot/modules/stickers.py
  tg_bot/modules/ud.py
  tg_bot/modules/userinfo.py
  tg_bot/modules/warns.py
  tg_bot/modules/weebify.py
  tg_bot/modules/welcome.py
  tg_bot/modules/wiki.py
  tg_bot/sample_config.py
Labels: bug, documentation, enhancement

#66 [Chatbot] group admins can now enable/disable chatbot.
  SaitamaRobot/modules/chatbot.py
Labels: enhancement

#67 [welcome] fix a typo
  SaitamaRobot/modules/welcome.py
Labels: translation improvement

#69 Update __main__.py
  SaitamaRobot/__main__.py
Labels: enhancement

#71 Switch to context based handlers
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/dbcleanup.py
  SaitamaRobot/modules/dev.py
  SaitamaRobot/modules/disable.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/eval.py
  SaitamaRobot/modules/feds.py
Labels: enhancement

#72 Switch to context based handlers
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/get_common_chats.py
  SaitamaRobot/modules/gettime.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/grammar_correction.py
  SaitamaRobot/modules/gtranslator.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/log_channel.py
  SaitamaRobot/modules/math.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/modules.py
  SaitamaRobot/modules/muting.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/paste.py
  SaitamaRobot/modules/purge.py
  SaitamaRobot/modules/remote_cmds.py
  SaitamaRobot/modules/reporting.py
  SaitamaRobot/modules/rss.py
  SaitamaRobot/modules/shout.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/modules/welcome.py
Labels: enhancement

#73 [modules] import Update class
  SaitamaRobot/modules/eval.py
  SaitamaRobot/modules/rss.py
Labels: enhancement

#75 attempt to fix bugs #2
  SaitamaRobot/modules/afk.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/cleaner.py
  SaitamaRobot/modules/connection.py
  SaitamaRobot/modules/dbcleanup.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/reporting.py
  SaitamaRobot/modules/stickers.py
  SaitamaRobot/modules/wallpaper.py
Labels: bug

#76 attempt to fix v12 related bugs #3
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/locks.py
Labels: bug
