Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-07, with the labels that each got.

#95 Fixed a typo in gban reply message to user.
  SaitamaRobot/modules/global_bans.py
Labels: enhancement

#96 Added telethon Client for fast purge
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/helper_funcs/telethn/__init__.py
  SaitamaRobot/modules/helper_funcs/telethn/chatstatus.py
  SaitamaRobot/modules/purge.py
  SaitamaRobot/saitamabot.py
  SaitamaRobot/sample_config.py
  requirements.txt
Labels: enhancement, major change, more coffee needed

#98 [Admin.py] Get chatusername with proper link when using invite command
  SaitamaRobot/modules/admin.py
Labels: enhancement

#99 [admin.py] Use https invite link instead of http
  SaitamaRobot/modules/admin.py
Labels: enhancement

#100 [init.py] To capture logs in log.txt
  SaitamaRobot/__init__.py
Labels: enhancement

#103 Disable: fix commands are working even if they're disabled
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/disable.py
Labels: bug, critical bug

#104 Update app.json
  app.json
Labels: enhancement

#101 Added a message Count to fast purge
  SaitamaRobot/modules/purge.py
Labels: enhancement

#106 Add a workflow to Autoformat code
  .github/yapf.yml
Labels: enhancement, more coffee needed

#108 Fix some issues and add auto code format workflow
  .github/yapf.yml
  SaitamaRobot/sample_config.py
  app.json
Labels: enhancement

#110 workflows: fixed a foolish mistake
  .github/workflows/yapf.yml
Labels: bug, more coffee needed

#113 Notes : Monospaced note_name in bot reply msg
  SaitamaRobot/modules/notes.py
Labels: enhancement

#114 Fixes: fixed tban, ignore, brodcarst
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/users.py
Labels: bug

#117 [welcome] Bug fixes and stability improvments.
  SaitamaRobot/modules/welcome.py
Labels: bug

#118 workflows: set indent width to 4 with yapf style
  .github/workflows/yapf.yml
Labels: enhancement

#122 Notes : show the note num along with note name in note_list
  SaitamaRobot/modules/notes.py
Labels: enhancement

#129 Treewide: use identity for comparison with None
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/gtranslator.py
  SaitamaRobot/modules/purge.py
  SaitamaRobot/modules/reporting.py
  SaitamaRobot/modules/sql/connection_sql.py
  SaitamaRobot/modules/sql/feds_sql.py
  SaitamaRobot/modules/users.py
Labels: enhancement

#130 log channel: Fixed undefined variable bot
  SaitamaRobot/modules/log_channel.py
Labels: bug

#131 shell.py: fixed undefined variables f and bot
  SaitamaRobot/modules/shell.py
Labels: bug fix

#132 bl_stickers: fixed extract_time not defined
  SaitamaRobot/modules/blacklist_stickers.py
Labels: bug fix

#135 cust filters: Fixed module Re import
  SaitamaRobot/modules/cust_filters.py
Labels: enhancement

#134 Treewide: Removed unnecessary f-string's
  SaitamaRobot/modules/currency_converter.py
  SaitamaRobot/modules/dbcleanup.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/warns.py
Labels: enhancement

#139 Treewide: Fixed use on unneeded not
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/warns.py
Labels: enhancement

#140 Stickers: Add animated stickers kanging support
  SaitamaRobot/modules/stickers.py
Labels: enhancement

#149 Shiken >> Master
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/antiflood.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/cleaner.py
  SaitamaRobot/modules/connection.py
  SaitamaRobot/modules/currency_converter.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/muting.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/reporting.py
  SaitamaRobot/modules/rss.py
  SaitamaRobot/modules/rules.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/modules/welcome.py
  app.json
Labels: example of what not to do, more coffee needed
