Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-09, with the labels that each got.

#195 Bring docker and some more updates to master branch
  SaitamaRobot/Dockerfile
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/rules.py
  SaitamaRobot/modules/sql/welcome_sql.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/sample_config.py
Labels: Code Formatting, bug fix, documentation, enhancement, major change, more coffee needed

#197 Corrected paths in codeowners
  .github/CODEOWNERS
Labels: bug fix

#200 Fix hyperlinking results in /kaizoku listing
  SaitamaRobot/modules/anime.py
Labels: bug fix

#205 Bring HP system and stability to master branch
  .github/workflows/docker.yml
  .gitignore
  Dockerfile
  Procfile
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/fun_strings.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/sample_config.py
  exp.sh
Labels: Code Formatting, bug fix, documentation, enhancement, major change, more coffee needed, translation improvement

#206 Bring HP system and stability to master branch
  .github/workflows/docker.yml
  .gitignore
  Dockerfile
  Procfile
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/fun_strings.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/sample_config.py
  exp.sh
Labels: bug fix, documentation, enhancement, major change, more coffee needed, translation improvement

#209 [rules] Update response text for /rules to a sensible one
  SaitamaRobot/modules/rules.py
Labels: translation improvement

#219 Bring new changes to master branch
  .github/CODEOWNERS
  .github/workflows/docker_disabled.yml
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  Git_Pull.bat
  Git_Push.bat
  Procfile
  README.md
  SaitamaRobot/__init__.py
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/afk.py
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/fun_strings.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/log_channel.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/rules.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/sample_config.py
  exp.sh
  heroku.yml
Labels: Code Formatting, bug fix, documentation, enhancement, major change, more coffee needed, translation improvement

#229 fix HeroKu WebHooks
  SaitamaRobot/__main__.py
Labels: bug fix
