Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-11, with the labels that each got.

#277 [afk] Ignore case when user says "Brb"
  SaitamaRobot/modules/afk.py
Labels: bug fix

#292 Added wall api to app.json, fixed typo in kang and added help for /wall
  SaitamaRobot/modules/misc.py
  app.json
Labels: documentation, enhancement

#301 Pulling some fixes and updates to master
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/admin.py
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/purge.py
  SaitamaRobot/modules/reporting.py
  SaitamaRobot/modules/sql/cust_filters_sql.py
  requirements.txt
Labels: bug fix, documentation, enhancement
