Repository AnimeKaizoku/SaitamaRobot, pull requests merged in 2020-08, with the labels that each got.

#165 Merge shiken to master
  SaitamaRobot/__init__.py
  SaitamaRobot/modules/anime.py
  SaitamaRobot/modules/antiflood.py
  SaitamaRobot/modules/backups.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/connection.py
  SaitamaRobot/modules/currency_converter.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/gettime.py
  SaitamaRobot/modules/helper_funcs/alternate.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/muting.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/remote_cmds.py
  SaitamaRobot/modules/sql/antiflood_sql.py
  SaitamaRobot/modules/sql/connection_sql.py
  SaitamaRobot/modules/ud.py
  SaitamaRobot/modules/welcome.py
  SaitamaRobot/sample_config.py
Labels: bug fix, documentation, enhancement

#167 Send output as a file.
  SaitamaRobot/modules/eval.py
Labels: enhancement

#187 Shiken >> Master
  .gitignore
  SaitamaRobot/modules/afk.py
  SaitamaRobot/modules/bans.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/chatbot.py
  SaitamaRobot/modules/cleaner.py
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/debug.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/helper_funcs/chat_status.py
  SaitamaRobot/modules/helper_funcs/handlers.py
  SaitamaRobot/modules/helper_funcs/misc.py
  SaitamaRobot/modules/helper_funcs/msg_types.py
  SaitamaRobot/modules/helper_funcs/string_handling.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/log.py
  SaitamaRobot/modules/muting.py
  SaitamaRobot/modules/ping.py
  SaitamaRobot/modules/sql/blacklist_sql.py
  SaitamaRobot/modules/sql/cust_filters_sql.py
  SaitamaRobot/modules/sql/warns_sql.py
  SaitamaRobot/modules/stickers.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/mwt.py
  SaitamaRobot/sample_config.py
  SetupVirtualEnv_run_once.bat
  app.json
  requirements.txt
  restart.bat
  start.bat
  start_service.bat
Labels: Code Formatting, bug fix, documentation, enhancement, major change, more coffee needed

#191 More upgrades to master version
  SaitamaRobot/modules/backups.py
  SaitamaRobot/modules/blacklist.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/connection.py
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/disable.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/helper_funcs/msg_types.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/log_channel.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/notes.py
  SaitamaRobot/modules/rules.py
  SaitamaRobot/modules/sql/welcome_sql.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/modules/warns.py
  SaitamaRobot/modules/welcome.py
Labels: enhancement, major change

#193 Push minor edits and improvements to master
  SaitamaRobot/__main__.py
  SaitamaRobot/modules/antiflood.py
  SaitamaRobot/modules/backups.py
  SaitamaRobot/modules/blacklist_stickers.py
  SaitamaRobot/modules/blacklistusers.py
  SaitamaRobot/modules/connection.py
  SaitamaRobot/modules/currency_converter.py
  SaitamaRobot/modules/cust_filters.py
  SaitamaRobot/modules/disasters.py
  SaitamaRobot/modules/feds.py
  SaitamaRobot/modules/fun.py
  SaitamaRobot/modules/global_bans.py
  SaitamaRobot/modules/gtranslator.py
  SaitamaRobot/modules/locks.py
  SaitamaRobot/modules/misc.py
  SaitamaRobot/modules/paste.py
  SaitamaRobot/modules/ping.py
  SaitamaRobot/modules/reactions.py
  SaitamaRobot/modules/remote_cmds.py
  SaitamaRobot/modules/shout.py
  SaitamaRobot/modules/sql/connection_sql.py
  SaitamaRobot/modules/sql/feds_sql.py
  SaitamaRobot/modules/ud.py
  SaitamaRobot/modules/userinfo.py
  SaitamaRobot/modules/users.py
  SaitamaRobot/modules/weebify.py
  SaitamaRobot/modules/wiki.py
Labels: Code Formatting, bug fix, enhancement, translation improvement
